version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: bincom_test
      TZ: UTC
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
